name: merge

on:
  workflow_run:
    workflows:
      - push
    branches:
      - develop
    types:
      - completed
jobs:
  merge:
    name: merge
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install dependencies
        run: npm ci
      - name: run build
        run: npm run build
      - uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
